import { describe, expect, it } from "vitest";
import { buildClientesData } from "@/lib/clientes/build-data";

describe("buildClientesData", () => {
  it("mapeia clientes com etapa, responsável, valor, tarefas e próxima reunião", () => {
    const result = buildClientesData({
      stages: [
        {
          id: "stage-1",
          name: "Briefing",
          slug: "briefing",
          color: "#2563eb",
          order_index: 2,
          is_active: true,
          is_final: false,
        },
      ],
      clients: [
        {
          id: "cliente-1",
          code: "CLI-001",
          nomecliente: "Acme Brasil",
          nome: null,
          nome_fantasia: "Acme",
          whatsapp: "11999999999",
          email: "ops@acme.test",
          instagram: "@acme",
          company_name: "Acme Ltda",
          company_cnpj: "00.000.000/0001-00",
          segment: "Food",
          subsegment: "Delivery",
          segmento_id: "seg-1",
          subsegmento_id: "sub-1",
          valor: 1000,
          deal_value: 900,
          celebridade: "Celebridade A",
          praca: "São Paulo",
          classificacao: "A",
          current_stage_id: "stage-1",
          stage_entered_at: "2026-05-10T12:00:00.000Z",
          created_at: "2026-05-01T12:00:00.000Z",
          responsavel_atendimento: "profile-1",
          assigned_to: null,
          prazo_final: "2026-05-20",
          vigencia: "2026-06-01",
          data_contrato_assinado: "2026-05-02",
          inicio_vigencia: "2026-05-05",
          is_archived: false,
          archived_at: null,
          link_pasta_drive: "https://drive.test/acme",
          link_proposta: "https://proposal.test/acme",
          link_pasta_entrega: "https://delivery.test/acme",
        },
        {
          id: "cliente-2",
          code: null,
          nomecliente: null,
          nome: "Arquivado",
          nome_fantasia: null,
          whatsapp: null,
          email: null,
          instagram: null,
          company_name: null,
          company_cnpj: null,
          segment: null,
          subsegment: null,
          segmento_id: null,
          subsegmento_id: null,
          valor: null,
          deal_value: 300,
          celebridade: null,
          praca: null,
          classificacao: null,
          current_stage_id: null,
          stage_entered_at: null,
          created_at: "2026-04-01T12:00:00.000Z",
          responsavel_atendimento: null,
          assigned_to: null,
          prazo_final: null,
          vigencia: null,
          data_contrato_assinado: null,
          inicio_vigencia: null,
          is_archived: true,
          archived_at: "2026-05-15T12:00:00.000Z",
          link_pasta_drive: null,
          link_proposta: null,
          link_pasta_entrega: null,
        },
      ],
      profiles: [{ id: "profile-1", full_name: "Ana Produção", avatar_url: null }],
      segmentos: [{ id: "seg-1", nome: "Alimentos" }],
      subsegmentos: [{ id: "sub-1", nome: "Delivery Premium" }],
      tasks: [
        {
          id: "task-1",
          cliente_id: "cliente-1",
          title: "Revisar briefing",
          status: "open",
          priority: "high",
          is_urgent: true,
          deadline: "2026-05-18",
          created_at: "2026-05-16T12:00:00.000Z",
          started_at: null,
          assigned_to: "profile-1",
          pipeline_stage_id: "stage-1",
        },
      ],
      meetings: [
        {
          id: "meeting-1",
          cliente_id: "cliente-1",
          title: "Alinhamento",
          scheduled_at: "2026-05-19T14:00:00.000Z",
          duration_minutes: 30,
          meeting_type: "online",
          meeting_link: "https://meet.test/acme",
          status: "scheduled",
          organizer_id: "profile-1",
        },
      ],
      now: new Date("2026-05-18T12:00:00.000Z"),
    });

    expect(result.items).toHaveLength(2);
    expect(result.items[0]).toMatchObject({
      id: "cliente-1",
      nome: "Acme Brasil",
      stageName: "Briefing",
      stageOrder: 2,
      responsavelNome: "Ana Produção",
      segmentoNome: "Alimentos",
      subsegmentoNome: "Delivery Premium",
      vigenciaFinal: "2026-06-01",
      valor: 1000,
      tarefasAbertas: 1,
      tarefasUrgentes: 1,
      isArchived: false,
      nextMeetingAt: "2026-05-19T14:00:00.000Z",
    });
    expect(result.items[0].diasNaEtapa).toBe(8);
    expect(result.items[1]).toMatchObject({
      id: "cliente-2",
      nome: "Arquivado",
      isArchived: true,
      valor: 300,
    });
    expect(result.stages).toEqual([
      {
        id: "stage-1",
        name: "Briefing",
        slug: "briefing",
        color: "#2563eb",
        order_index: 2,
        is_final: false,
        is_active: true,
      },
    ]);
  });
});
